### ISSUE TITLE
Environment-specific notes in challenge descriptions

### ISSUE THREAD

**Issue by zardus** [pwncollege/ctf-archive#1]
Sometimes, challenges have environment-specific notes in their descriptions (e.g., https://github.com/pwncollege/ctf-archive/blob/main/0ctf2017/module.yml#L14). We should add some sort of Editor's Note about that when these are no longer accurate.

**Comment by prathamgupta36** [comment]
Added notes to the ones needed and made sure incompatible challenges are not visible for now.
