### ISSUE TITLE
Export challenge descriptions to DESCRIPTION.md

### ISSUE THREAD

**Issue by zardus** [pwncollege/ctf-archive#2]
Rather than keep the challenge descriptions in `module.yml`, I think we should move them to `challenge/DESCRIPTION.md`. I think that'll it make it more nicely self contained (and the yml simpler).

**Comment by prathamgupta36** [comment]
I moved the challenge descriptions to `DESCRIPTION.md` inside the challenge folder and removed them from their respective `module.yml` file
