### ISSUE TITLE
Compatibility Update: Support for glibc 2.34

### ISSUE THREAD

**Issue by prathamgupta36** [pwncollege/ctf-archive#4]
Some challenges (e.g., https://github.com/pwncollege/ctf-archive/tree/main/patriotctf/guessinggame) require glibc 2.34 for proper functionality, the challenges run smoothly on Ubuntu 22.04, which has glibc 2.34 but upgrading to this version is not feasible at the moment. We should find a to have the correct files and path for those specific challenges.

**Comment by zardus** [comment]
Can we plop the libc in `/challenge` and set the rpath on the binary, or am I missing something?

**Comment by prathamgupta36** [comment]
The way you suggested is working for other challenges which have the libc files in their github and I am trying to apply it for the ones that need the newer version. I tried using docker to pull the necessary files but I am not sure why the system gives corruption error. I am thinking of trying to update the system and find the necessary files to use them separately.

**Comment by prathamgupta36** [comment]
I was trying to export the libc files but in the new environment with the exported files, basic commands like `ls`, `ldd` are giving seg faults or seg fault (core dump)

**Comment by zardus** [comment]
Are you overwriting the container's libc? We shouldn't do that. Instead, put the challenge libc in `/challenge`, and use patchelf to update the rpath of the challenge to search for libraries in `/challenge`

**Comment by prathamgupta36** [comment]
That makes sense, I was using patchelf for the previous ones. I used this: `patchelf --set-rpath /challenge/glibc/lib/x86_64-linux-gnu:/challenge/glibc/lib64 /challenge/guessinggame` which fixes the issue when I check with `ldd` but running challenge gives me seg fault

**Comment by prathamgupta36** [comment]
There is a compatibility issue in dynamic linking and I think it might be this file `linux-vdso.so.1` which I think is kernel specific so I am not sure if there is a way to use the binary made in Ubuntu 22.04 in 20.04

**Comment by prathamgupta36** [comment]
Created new binaries that are compatible with the current environment.

**Comment by zardus** [comment]
Can you elaborate on this? Ideally, we'd use the original binaries whenever possible and just have `.init` update their rpath and so on.
