### ISSUE TITLE
Install SageMath for Challenge Environment

### ISSUE THREAD

**Issue by prathamgupta36** [pwncollege/ctf-archive#7]
This [challenge](https://github.com/pwncollege/ctf-archive/tree/main/0ctf2019/babyrsa) requires sage math to run the given files, after installing sage math in the environment by using ```sudo apt install sagemath-jupyter``` the challenge works but looking for a better dynamic solution

**Comment by zardus** [comment]
You can add this as a PR against the dojo itself; we can just install sage
into the standard container

**Comment by prathamgupta36** [comment]
I added the `sage` file and it is moved to the location where I found it after installation using the `.init` file

**Comment by prathamgupta36** [comment]
how do I add sage to the standard container? There seem to be a good amount of challenges using sage

**Comment by prathamgupta36** [comment]
Added PR to dojo for sagemath
