### ISSUE TITLE
Question about rehosting

### ISSUE THREAD

**Issue by reteps** [pwncollege/ctf-archive#8]
In this document, https://github.com/pwncollege/ctf-archive/blob/main/CONTRIBUTING.md#troubleshooting-flag-issues, you explain that you can create a simple "flag checker" binary. I assume it is important that the binary has permissions `700`?

**Comment by prathamgupta36** [comment]
If you are in the pwn.college server and after you are done with making the `flagCheck` binary, I would run `chmod +x flagCheck` and have it in the `/challenge/flagCheck` location. Also if you used `pyinstaller` like `pyinstaller --onefile flagCheck.py`, you get a binary executable that has the permissions.

**Comment by prathamgupta36** [comment]
I gave a rudimentary example in the file(https://github.com/pwncollege/ctf-archive/blob/main/CONTRIBUTING.md#troubleshooting-flag-issues) but have shifted towards using SHA-256 for encrypting the challenge flags
